//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.03 at 11:11:50 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://scape-project.eu/tool", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.scape_project.pt.tool;
