<?xml version="1.0" encoding="utf-8"?>
<!--
/*******************************************************************************
* Copyright (c) #GLOBAL_YEAR# The #GLOBAL_PROJECT_PREFIX# Project Partners.
*
* All rights reserved. This program and the accompanying
* materials are made available under the terms of the
* Apache License, Version 2.0 which accompanies
* this distribution, and is available at
* http://www.apache.org/licenses/LICENSE-2.0
*
*******************************************************************************/
-->
<wsdl:definitions xmlns:tns="http://#PROJECT_PACKAGE_PATH#"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	targetNamespace="http://#PROJECT_PACKAGE_PATH#">

    <wsdl:documentation>
        #SERVICE_DESCRIPTION#
    </wsdl:documentation>

    <wsdl:types>
        <xsd:schema xmlns="http://schemas.xmlsoap.org/wsdl/" attributeFormDefault="qualified" 
        elementFormDefault="qualified" targetNamespace="http://#PROJECT_PACKAGE_PATH#"/>
    </wsdl:types>

    <wsdl:portType name="#GLOBAL_PROJECT_PREFIX#ServicePortType">
    </wsdl:portType>

    <wsdl:binding name="#GLOBAL_PROJECT_PREFIX#ServiceSOAP11Binding" type="tns:#GLOBAL_PROJECT_PREFIX#ServicePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
    </wsdl:binding>
    
    <wsdl:service name="#GLOBAL_PROJECT_PREFIX##PROJECT_MIDFIX#Service">
        <wsdl:port name="#GLOBAL_PROJECT_PREFIX#ServiceSOAP11port_http"  binding="tns:#GLOBAL_PROJECT_PREFIX#ServiceSOAP11Binding">
            <soap:address location="http://#TOMCAT_PUBLIC_HOST#:#TOMCAT_PUBLIC_HTTP_PORT#/#TOMCAT_PUBLIC_AXIS_CONTEXT#/#TOMCAT_PUBLIC_SERVICES_PATH#/#GLOBAL_PROJECT_PREFIX##PROJECT_MIDFIX#Service" />
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>